# The URL the site will be built for
base_url = "//archie-zola.vercel.app/"

title = "Blog"

compile_sass = true
build_search_index = true

taxonomies = [
    {name = "tags"}
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "OneHalfLight"

[extra]

# control dark mode: auto | dark | toggle
mode = "toggle"

# interal CDN resource
useCDN = true

favicon = "/icon/favicon.png"

copyright = "keith"

# config menu path
[[extra.menu]]
name = "/posts"
url = "/"
weight = 1


[[extra.menu]]
name = "/projects"
url = "/projects"
weight = 2

[[extra.menu]]
name = "/about"
url = "/about"
weight = 3

[[extra.social]]
icon = "twitter"
name = "Twitter"
url = "https://github.com/not-matthias/"

[[extra.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/not_matthias/"

