base_url = "not-matthias.github.io"
title = "Personal Blog"
compile_sass = true
build_search_index = true

taxonomies = [
    {name = "tags"}
]

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
use_cdn = true
favicon = "/icon/favicon.png"

[extra.analytics]
enabled = true
goatcounter_user = "not-matthias"
goatcounter_host = "example.com"    # default: goatcounter.com

[[extra.menu]]
name = "/posts"
url = "/"
weight = 1

[[extra.menu]]
name = "/projects"
url = "/projects"
weight = 2

[[extra.menu]]
name = "/about"
url = "/about"
weight = 3

[[extra.social]]
icon = "twitter"
name = "Twitter"
url = "https://github.com/not-matthias/"

[[extra.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/not_matthias/"

